### PR TITLE
Create PasswordStrengthChecker.cs in C# language

### PR DESCRIPTION
**Pull request by deadmann**
create C# based file to be used for server side re-checking of the password...

### CODE REVIEW

**Comment by elboletaire** [comment]
I'm sorry but I really don't get this PR. Shouldn't this C# code be an independent package? :confused:

**Comment by elboletaire** [comment]
I'd like to see this merged for v2 (which I'm currently working on), but I miss some things:

- Use widget settings for things like the blue color (forced by you to 10), or for the max color (forced by you to 240).
- Split the code into smaller functions.
- Add a test (or tests). All that ternary operators are confusing and add a lot of cyclomatic complexity. They should, at least, be properly tested to ensure all the conditions.
- There's a typo in the option varname, you spelled `Imge` instead of `Image`

**Comment by elboletaire** [comment]
I accidentally sent a message to this thread when was for another PR. Sorry if you've been notified for it.

**Comment by deadmann** [comment]
think about it like this:
i have js based client, what if you provide another service, or someone gonna cheat on your rule? well sure it's their own deciesion to let other people steal their data, but it's good that we do these checks in server too just in case, and when we do not use nodeJS that support or current language...

**Comment by elboletaire** [comment]
Well, this is a front-end project, and it will remain like so. If you still think this can be a nice feature, you're free to create a custom project. If it's properly coded and documented I'll be happy to link it into my readme, as a _backend alternative_ (note that I'm also currently working on the nodejs implementation of this code..).

**Pull request closed without merging**
