### PR TITLE
Color bar

### PR DESCRIPTION
**Pull request by jhoover4**
Had to change the eslint file as its checking for es6 features, but also enforcing es5. I'm going to open another ticket to change that.

It also might be best to just remove the image altogether and take out the "useColorImage" property, not sure if that complexity is needed.

### CODE REVIEW

**Comment by elboletaire** [comment]
Really nice work @jhoover4. Let me some days to check it and accept it. I think that I'll have some time this same week. Otherwise I'll have a lot of time in a few weeks, as I've just quit my current work.

**Comment by jhoover4** [comment]
@elboletaire How's work? I'm going to try to get through a few more of these this week, let me know if you'll have time to review!

**Comment by elboletaire** [comment]
Hey @jhoover4 I've this almost merged in my local workdir. But there's something I don't like, and I'd like your opinion on it:

The `blue` param in `customColorBarRGB`, I think it should have the exact same format than the other two colors. Is it possible? Right now is a bit weird having to configure the blue different than the other two colors.

BTW, I've created a branch (`f/color-bar`) where you can see the current progress on this merge*. I've changed some things like:

- Changed varname to `useColorBarImage` and set by default to false. I don't like to change the default behavior, if anyone wants to use the css colorbar, they can enable it as soon as we publish the new release.
- Re-enabled the `no-prototype-builtins` eslint check, and made the required changes to the code to be complaint against this rule.

\* Please, if you do any changes, remember to merge `f/color-bar` with your branch, or directly create a branch from that one first.

**Comment by adbakke** [comment]
Any chance you'll merge this in?

**Comment by jhoover4** [comment]
Oh man, haven't taken a look at this in a bit. @elboletaire you still need this merged? Happy to work on it this weekend and go off the branch you referenced

**Comment by elboletaire** [comment]
It's nice that you just say something because otherwise I was gonna do it during this week. So yes, if you can take a look into it and change it to make it configurable as stated in my previous comment I'll merge it as soon as it's done 😄

**Comment by jhoover4** [comment]
Let's do it man. I'll get something up soonish then

**Comment by jhoover4** [comment]
Alrighty, I've got everything up to date and made those eslint changes. Its been awhile, but I believe I had the blue setup like that because you need some base color for the percentage calculations. In other words, there's no min and max blue, it has to be stable, or the whole thing won't make sense.

Maybe I can add some documentation in the README explaining that?

**Comment by elboletaire** [comment]
@jhoover4 yeah a small note in the readme would be nice. I don't recall if there's a specific section for this specific configuration. If you think it's a good moment to add such section, go ahead :)

**Comment by jhoover4** [comment]
I was thinking about adding it in the README, but I think it might be too confusing. Lets just leave it. Its ready to pull in!

**Pull request merged**
