### PR TITLE
Calculate color instead changing background position

### PR DESCRIPTION
**Pull request by hmichal-dev**
Add option to calculate colorbar color instead using background image.

### CODE REVIEW

**Comment by hmichal-dev** [comment]
Travis test failed due to incorrect configuration

**Comment by elboletaire** [comment]
Yeah apparently I broke something when writing another package. I'll try to get it fixed asap.

**Comment by elboletaire** [comment]
BTW, what does this feature exactly do? Allows us to not use a bg image for the progress bar?

**Comment by hmichal-dev** [comment]
Yes, this feature allow us to not use image as background. Background (color of progress bar) is calculated dynamically and goes from green via yellow to red. To keep backward compatibility image is used by default.

In current version image still loeds until css is overwriten by user. This can be changed by adding diffrent classes when using option useColorBarImge is false - this is a thing for future development.

**Comment by elboletaire** [comment]
I'd like to see this merged for v2 (which I'm currently working on), but I miss some things:

- Use widget settings for things like the blue color (forced by you to 10), or for the max color (forced by you to 240).
- Split the code into smaller functions.
- Add a test (or tests). All that ternary operators are confusing and add a lot of cyclomatic complexity. They should, at least, be properly tested to ensure all the conditions.
- There's a typo in the option varname, you spelled `Imge` instead of `Image`

**Comment by jhoover4** [comment]
I'm going to get this pushed up in a new PR next with your recommendations.

**Comment by jhoover4** [comment]
Alrighty, new PR for this #28

**Comment by elboletaire** [comment]
Superseeded by #28

**Pull request closed without merging**
