### PR TITLE
Custom strength steps (ranges)

### PR DESCRIPTION
**Pull request by hmichal-dev**
You can define custom steps in options. Steps must be sorted ascending.

~~~javascript
var config = {
    customSteps: {
      0: 'Really insecure password. You never should use it.',
      30: 'Insecure password',
      50: 'Hmm....',
      75: 'Strong password',
      95: 'Yeah! Really strong password'
    }
  }
$('#password').password(config);
~~~

### CODE REVIEW

**Comment by hmichal-dev** [comment]
Travis test failed due to incorrect configuration

**Comment by elboletaire** [comment]
Nice, I thought previously in adding a feature like this.

Could you please add a test to check if it works as expected?

**Comment by hmichal-dev** [comment]
@elboletaire I can't write JavaScript tests. I'm a backend developer.

**Comment by elboletaire** [comment]
I don't understand that argument. I'm a backend developer and I test both backend and frontend, and they are tested the same way. Actually, the tests run in this project are run exactly like any backend tests, but using libraries to simulate there's a DOM.

Just take a look to the test file, and also to this part of the readme where you can see how tests are executed: https://github.com/elboletaire/password-strength-meter#testing

BTW, if you really think you cannot do it, let me know and I'll do it for you when I can.

**Comment by hmichal-dev** [comment]
I test backend but I don't know any framework for testing JavaScript. I'm busy in this month so I can't spend time learning it.

**Comment by elboletaire** [comment]
refs #11

**Comment by jhoover4** [comment]
Do we still need a test for this? I'd be happy to help.

**Comment by elboletaire** [comment]
Thanks @jhoover4, but I'm refactoring entirely. That's why I've tagged it for the version 2.0.0, because it'll bring breaking changes:

- I'll remove the old behavior. Now all strings will be defined as an object, like hmichal-dev did, but removing the old behavior.
- We need tests for everything. If I didn't this before is because that loop caused weird behaviors in some cases. We need to test all the possible cases.
- There are missing cases in hmichal-dev implementation (like the `min characters` or the `contains username field text` errors).

Also, for v2 there are other issues on track: https://github.com/elboletaire/password-strength-meter/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0

**Comment by jhoover4** [comment]
For sure, makes sense. I guess I was just offering to help with the overall refactoring if you need it! If not, no worries.

**Comment by elboletaire** [comment]
Ofc you can do it if you take all that in mind. I'm probably not gonna work on it until next weekend or so; you're free to take any of the issues for the V2 (even for V3 if you want) and make a PR.

**Comment by jhoover4** [comment]
Sweet, I'll try to push up this and the other issue I commented on.

**Comment by jhoover4** [comment]
Okay I added a PR for this #26

**Comment by elboletaire** [comment]
Superseeded by #26

**Pull request closed without merging**
