### PR TITLE
Custom steps with test

### PR DESCRIPTION
**Pull request by jhoover4**
I've duplicated @hmichal-dev 's work and added testing. Also added some semicolons, I know its syntactic sugar, but it makes JS happy.

### CODE REVIEW

**Comment by elboletaire** [comment]
Let's see if we can merge this with the current 2.0 branch and publish it along it.

**Comment by jhoover4** [comment]
Okay easy enough

**Comment by elboletaire** [comment]
I've just accepted the colorbar PR to v2. Tell me something if you fix the issues here, otherwise I'll try to do it by myself this wednesday :)

**Comment by elboletaire** [comment]
Superseeded by #35

**Pull request closed without merging**
